### ISSUE TITLE
When does sitemaps.add() run?  Is it once, at server restart, or when?

### ISSUE THREAD

**Issue by JohnAllen** [gadicc/meteor-sitemaps#13]
We're wondering when the sitemap is actually created, because according to the docs, it doesn't appear that we manually call it anywhere, it just runs at some time.   When does it run?  

If it does run more than one time, it should duplicate the sitemap but the duplicate will have the updated collection info, which is something we need.  Our collection contains ~17,000 companies and they change over time so we would like our sitemap to be updated periodically, say about once a month.

Also, somewhat related is, if it runs on some regular basis, does it delete and recreate the sitemap each time or will we need to manually remove it every time it runs?

**Comment by cyclops24** [comment]
Hey,
I think this issue is related to my problem. I post a question [here](http://stackoverflow.com/questions/32003812/sitemap-not-created-until-server-restart-in-meteor) on stacjoverflow. Thanks if you see that.
