### ISSUE TITLE
Recent Iron router #! change causes redirect loop

### ISSUE THREAD

**Issue by jimmiebtlr** [gadicc/meteor-sitemaps#23]
Navigating to /sitemap.xml results in a redirect loop between /#!sitemap.xml and /sitemap.xml.  

Not sure if this should be considered an iron:router bug or a sitemaps bug. 

Any thoughts, on what to check or where the issue may be?

**Comment by jimmiebtlr** [comment]
It seems to have fixed itself when trying to determine the cause for some other SEO related issues.

**Comment by gadicc** [comment]
Great, thanks for letting us know.  If you figure out what exactly you changed, feel free to report back in case it helps others.

**Comment by jimmiebtlr** [comment]
I removed appcache, and it started working.  Then I decided I would rather have appcache for the moment than spiderable and it continued to work.

Since, this doesn't seem very likely to be the actual fix I'm guessing something in the build wasn't getting correctly refreshed and one of my previous actions was the actual refresh.  In other words I'm really not sure what I did to fix it.
