### ISSUE TITLE
Customize root URL

### ISSUE THREAD

**Issue by yourcelf** [gadicc/meteor-sitemaps#26]
Currently, sitemaps' URLs are all based on ``Meteor.absoluteUrl()``, which in turn draws from the ``ROOT_URL`` environment variable.  Over at TelescopeJS/Telescope#891, we're trying to allow sites' root URLs to be user-configurable (using mongo-stored settings), so we need a way to set the root URL that doesn't involve changing environment variables.

Would you accept a PR to take a third argument on ``sitemaps.add`` which optionally specifies the root URL?

**Comment by gadicc** [comment]
Hi, thanks for your patience.  Sorry for the late reply, and actually, another PR came in for this too.  I finalized the API as follows:

`sitemaps.config('rootUrl', 'customRootUrl')`;

Please try out v0.0.21 and let me know if suits your needs.

**Comment by gadicc** [comment]
And re-open the issue if not.
