### ISSUE TITLE
Getting error when adding package to project in package file sitemaps.js

### ISSUE THREAD

**Issue by sandeepmirpuri** [gadicc/meteor-sitemaps#36]
![screen shot 2016-02-16 at 15 27 19](https://cloud.githubusercontent.com/assets/11516337/13067273/78638732-d4c2-11e5-9bb6-acac4a7a9438.png)
![screen shot 2016-02-16 at 15 28 00](https://cloud.githubusercontent.com/assets/11516337/13067272/78622338-d4c2-11e5-9a4c-3965dc3aebb9.png)

**Comment by ayhid** [comment]
I had the same problem just after updating the lodash version, I thinks it's related to the fact that the contains() method was removed in favor of includes() method

[](https://github.com/lodash/lodash/wiki/Changelog)

**Comment by gadicc** [comment]
hey, thanks @ayhid (and @sandeepmirpuri for your patience!).  I've published a new `v0.0.24` which correctly depends on underscore as required in Meteor 1.2+, and should avoid a conflict with a globally instaled lodash if it exists.  Can you confirm?

**Comment by ayhid** [comment]
@gadicc works like a charm thanks for the quick fix

**Comment by gadicc** [comment]
thanks for reporting back!
