### ISSUE TITLE
how to import with meteor 1.3 ?

### ISSUE THREAD

**Issue by lyquocnam** [gadicc/meteor-sitemaps#41]
how to import with meteor 1.3 ?
i tried `import 'meteor/gadicohen:sitemaps';`

and error:

`ReferenceError: sitemaps is not defined`

**Comment by sungwoncho** [comment]
Did you try `import {sitemaps} from 'meteor/gadicohen:sitemaps';`?

**Comment by lyquocnam** [comment]
thanks @sungwoncho
