### ISSUE TITLE
gzip

### ISSUE THREAD

**Issue by sungwoncho** [gadicc/meteor-sitemaps#43]
I'd love to help implement gzip (see [here](https://github.com/gadicc/meteor-sitemaps/blob/master/sitemaps.js#L54)). How can we proceed?

**Comment by gadicc** [comment]
@sungwoncho, I'm really sorry I never replied to this, especially since I really could have used the help!  :/  Fortunately @nlhuykhang has come to the rescue, and this was implemented in #48, shipped in v0.0.26.
