### ISSUE TITLE
sitemaps for multiple domain name single app

### ISSUE THREAD

**Issue by chongwang87** [gadicc/meteor-sitemaps#46]
i have exact same issue like this meteor forum post https://forums.meteor.com/t/using-meteor-with-multiple-domains

we have an app for multiple domain name, and the only way to get the domain name is from req.headers.host, can you add in the "req" or "req.headers" object to sitemaps.add function just like the solutions suggested in the forum post?

**Comment by nlhuykhang** [comment]
@chongwang87 
#47 the newest version will match your need

**Comment by Taakn** [comment]
Seems like this is causing a problem with the robots.txt since the sitemap added automatically there does not match the domain name.
