### ISSUE TITLE
First two values returned from collection ignored

### ISSUE THREAD

**Issue by c6y** [gadicc/meteor-sitemaps#49]
Hi, I'm trying to generate a sitemap. I have a collection "Quicks" that contains about a handful of search shortcuts. Each document of "Quicks" is rendered as an URL in the sitemap. For each I'd like to get the date of the last upload (to the collection "EboyPix") — and use it as the lastmod property for the sitemap.

When iterating through "Quicks" the first two return undefined for the createdAt field. As if function "getLatestQuickDate" needed a bit of time to get going.

What can I do? Thanks!

### /server/sitemap.js

    // Meteor
    import { sitemaps } from 'meteor/gadicohen:sitemaps';

    // Collections
    import { Quicks } from '../imports/api/quicks/quicks.js'; // contains search shortcuts
    import { EboyPix } from '../imports/api/eboypix/eboypix.js';

    const quicksLabels = Quicks.find().fetch();

    // Returns the latest date from the slug
    function getLatestQuickDate(slug) {
      const latestSlug = EboyPix.findOne(
        { tags: slug },
        { sort: { createdAt: -1, limit: 1 } }
      );
      if (latestSlug) {
        return latestSlug.createdAt;
      }
    }

    // Returns array of pages from Quicks collection
    const quicksLinks = function() {
      let quicksPagesAll = [];
      if (quicksLabels) {
        Object.keys(quicksLabels).forEach(function(key) {
          const slug = quicksLabels[key].slug.toString();
          const lastmod = getLatestQuickDate(slug);
          const quicksPage = {
            page: 'pool/' + quicksLabels[key].label + '/1',
            changefreq: 'weekly',
            priority: quicksLabels[key].rank,
            lastmod: lastmod
          };
          quicksPagesAll.push(quicksPage);
        });
        return quicksPagesAll;
      }
    };

    sitemaps.add('/sitemap.xml', function() {
      return quicksLinks();
    });

### output: /sitemap.xml

    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      <url>
        <loc>http://localhost:3000/pool/everything/1</loc>
        <changefreq>weekly</changefreq>
        <priority>1</priority>
      </url>
      <url>
        <loc>http://localhost:3000/pool/pixorama/1</loc>
        <changefreq>weekly</changefreq>
        <priority>0.9</priority>
      </url>
      <url>
        <loc>http://localhost:3000/pool/animations/1</loc>
        <lastmod>2017-02-24T08:22:37+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.1</priority>
      </url>
      <url>
        <loc>http://localhost:3000/pool/vehicles/1</loc>
        <lastmod>2017-02-02T08:53:21+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.5</priority>
      </url>
      <url>
        <loc>http://localhost:3000/pool/portraits/1</loc>
        <lastmod>2017-02-02T21:57:44+00:00</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.7</priority>
      </url>
    </urlset>

**Comment by nlhuykhang** [comment]
Are you sure that the first two items have `createdAt` field? Let try console.log the value of `latestSlug` in `getLatestQuickDate` prior to returning

**Comment by c6y** [comment]
Aww no, you are right! The first two items did not return anything as the function was searching in 'tags' only (which returns 0 documents matching for 'everything' and 'pixorama').

Thanks a lot — and so sorry to waste your time. :(
