### ISSUE TITLE
 package support 

### ISSUE THREAD

**Issue by Saeeed-B** [gadicc/meteor-sitemaps#55]
@gadicc Hello, Does your package support the new version of meteor?
And is it up to date with the Google update?
If you no longer support this package. Please let users know

**Comment by gadicc** [comment]
Hey @Saeeed-B 

I'm not aware of any Meteor updates that break support for this package.  If that should be the case, please let me know.  Likewise with sitemaps... I'm not sure which Google update you're referring to... so far as I know Google's last update to the sitemap standard was 2012 (multilanguage support).

I'm no longer working in Meteor but I do try ensure my packages remain usable.

Thanks!

**Comment by Saeeed-B** [comment]
Thanks a lot
According to my experiments, there is still no problem, but there will certainly be problems with older packages in the near future.
The meteorite community is somewhat disgusted. Because packages that play a very important role are very old and no longer supported.

I try to assign basic packages so that users' tasks are also specified.
So I asked you to either announce or give up if you are not able to support and update the package.

tanks again
