### ISSUE TITLE
robots.txt smart package required ?

### ISSUE THREAD

**Issue by TimoRuetten** [gadicc/meteor-sitemaps#9]
Hey

I try your package but it seems not to be work. This is my file:

server/sitemaps.js

```
console.log('Adding to Sitemap');
sitemaps.add('/sitemap.xml', function() {
  return [
    { page: '/user/login', lastmod: new Date() , changefreq: 'monthly', priority: 0.8}
  ];
});
```

This do .... nothing. Absolutly nothing. My console.log is outputted in my server log, but no sitemap.xml was created. I tried to add a file by my self - a sitemap.xml file - but this will also not be updated with this package.

I read, that you add a line to robots.txt when using robots.txt package - but I do not use this and I dont want to - so do I need to use this package so your will work ?

**Comment by FakhruddinAbdi** [comment]
I have same issue @TimoRuetten now :) 
Where did you create the sitemap.xml ?

**Comment by gadicc** [comment]
hi @FakhruddinAbdi... sitemaps are "dynamic" (they're generated in real time at request time) and don't persist on any file on the disk.  You can check just by querying `/sitemaps.xml` on your site (or whatever location you chose).  I've clarified this in the README.

**Comment by FakhruddinAbdi** [comment]
Hi @gadicc .. Thanks for your quick response.
But honestly the README  is vague.. I couldn't understand how i should use. 
Even now i don't know what do you mean by `Querying /sitemaps.xml` 
Could you kindly just give me straight example.

**Comment by gadicc** [comment]
Oh, I meant if you navigate / browse to `http://localhost:3000/sitemaps.xml` (or whatever, you can test it).  I'll see if I can make the README a bit clearer a bit later.

**Comment by FakhruddinAbdi** [comment]
Thanks @gadicc . It does works now ..
I had one more mistake , I have used /sitemap`s`.xml instead of /sitemap.xml. So it didn't resolve the async function

**Comment by gadicc** [comment]
Great, @FakhruddinAbdi.  Thanks for reporting back :)
